#!/bin/bash
./sim_trace -t traces/4proc_validation -p MSI > Output/MSI_4.txt 2>&1
./sim_trace -t traces/4proc_validation -p MESI > Output/MESI_4.txt 2>&1
./sim_trace -t traces/4proc_validation -p MOSI > Output/MOSI_4.txt 2>&1
./sim_trace -t traces/4proc_validation -p MOESI > Output/MOESI_4.txt 2>&1
./sim_trace -t traces/4proc_validation -p MOESIF > Output/MOESIF_4.txt 2>&1
./sim_trace -t traces/8proc_validation -p MSI > Output/MSI_8.txt 2>&1
./sim_trace -t traces/8proc_validation -p MESI > Output/MESI_8.txt 2>&1
./sim_trace -t traces/8proc_validation -p MOSI > Output/MOSI_8.txt 2>&1
./sim_trace -t traces/8proc_validation -p MOESI > Output/MOESI_8.txt 2>&1
./sim_trace -t traces/8proc_validation -p MOESIF > Output/MOESIF_8.txt 2>&1
./sim_trace -t traces/16proc_validation -p MSI > Output/MSI_16.txt 2>&1
./sim_trace -t traces/16proc_validation -p MESI > Output/MESI_16.txt 2>&1
./sim_trace -t traces/16proc_validation -p MOSI > Output/MOSI_16.txt 2>&1
./sim_trace -t traces/16proc_validation -p MOESI > Output/MOESI_16.txt 2>&1
./sim_trace -t traces/16proc_validation -p MOESIF > Output/MOESIF_16.txt 2>&1
./sim_trace -t traces/experiment1 -p MSI > Output/experiment1/MSI.txt 2>&1
./sim_trace -t traces/experiment1 -p MESI > Output/experiment1/MESI.txt 2>&1
./sim_trace -t traces/experiment1 -p MOSI > Output/experiment1/MOSI.txt 2>&1
./sim_trace -t traces/experiment1 -p MOESI > Output/experiment1/MOESI.txt 2>&1
./sim_trace -t traces/experiment1 -p MOESIF > Output/experiment1/MOESIF.txt 2>&1
./sim_trace -t traces/experiment2 -p MSI > Output/experiment2/MSI.txt 2>&1
./sim_trace -t traces/experiment2 -p MESI > Output/experiment2/MESI.txt 2>&1
./sim_trace -t traces/experiment2 -p MOSI > Output/experiment2/MOSI.txt 2>&1
./sim_trace -t traces/experiment2 -p MOESI > Output/experiment2/MOESI.txt 2>&1
./sim_trace -t traces/experiment2 -p MOESIF > Output/experiment2/MOESIF.txt 2>&1
./sim_trace -t traces/experiment3 -p MSI > Output/experiment3/MSI.txt 2>&1
./sim_trace -t traces/experiment3 -p MESI > Output/experiment3/MESI.txt 2>&1
./sim_trace -t traces/experiment3 -p MOSI > Output/experiment3/MOSI.txt 2>&1
./sim_trace -t traces/experiment3 -p MOESI > Output/experiment3/MOESI.txt 2>&1
./sim_trace -t traces/experiment3 -p MOESIF > Output/experiment3/MOESIF.txt 2>&1
./sim_trace -t traces/experiment4 -p MSI > Output/experiment4/MSI.txt 2>&1
./sim_trace -t traces/experiment4 -p MESI > Output/experiment4/MESI.txt 2>&1
./sim_trace -t traces/experiment4 -p MOSI > Output/experiment4/MOSI.txt 2>&1
./sim_trace -t traces/experiment4 -p MOESI > Output/experiment4/MOESI.txt 2>&1
./sim_trace -t traces/experiment4 -p MOESIF > Output/experiment4/MOESIF.txt 2>&1
./sim_trace -t traces/experiment5 -p MSI > Output/experiment5/MSI.txt 2>&1
./sim_trace -t traces/experiment5 -p MESI > Output/experiment5/MESI.txt 2>&1
./sim_trace -t traces/experiment5 -p MOSI > Output/experiment5/MOSI.txt 2>&1
./sim_trace -t traces/experiment5 -p MOESI > Output/experiment5/MOESI.txt 2>&1
./sim_trace -t traces/experiment5 -p MOESIF > Output/experiment5/MOESIF.txt 2>&1
./sim_trace -t traces/experiment6 -p MSI > Output/experiment6/MSI.txt 2>&1
./sim_trace -t traces/experiment6 -p MESI > Output/experiment6/MESI.txt 2>&1
./sim_trace -t traces/experiment6 -p MOSI > Output/experiment6/MOSI.txt 2>&1
./sim_trace -t traces/experiment6 -p MOESI > Output/experiment6/MOESI.txt 2>&1
./sim_trace -t traces/experiment6 -p MOESIF > Output/experiment6/MOESIF.txt 2>&1
./sim_trace -t traces/experiment7 -p MSI > Output/experiment7/MSI.txt 2>&1
./sim_trace -t traces/experiment7 -p MESI > Output/experiment7/MESI.txt 2>&1
./sim_trace -t traces/experiment7 -p MOSI > Output/experiment7/MOSI.txt 2>&1
./sim_trace -t traces/experiment7 -p MOESI > Output/experiment7/MOESI.txt 2>&1
./sim_trace -t traces/experiment7 -p MOESIF > Output/experiment7/MOESIF.txt 2>&1
./sim_trace -t traces/experiment8 -p MSI > Output/experiment8/MSI.txt 2>&1
./sim_trace -t traces/experiment8 -p MESI > Output/experiment8/MESI.txt 2>&1
./sim_trace -t traces/experiment8 -p MOSI > Output/experiment8/MOSI.txt 2>&1
./sim_trace -t traces/experiment8 -p MOESI > Output/experiment8/MOESI.txt 2>&1
./sim_trace -t traces/experiment8 -p MOESIF > Output/experiment8/MOESIF.txt 2>&1
